# GALOIS FIELD GENERATED BY POLYNOMIAL X^4 + X + 1, alpha == X
def get_gf_16():
    return [
        1,  # alpha 0
        2,  # alpha 1
        4,  # alpha 2
        8,  # alpha 3
        3,  # alpha 4
        6,  # alpha 5
        12,  # alpha 6
        11,  # alpha 7
        5,  # alpha 8
        10,  # alpha 9
        7,  # alpha 10
        14,  # alpha 11
        15,  # alpha 12
        13,  # alpha 13
        9,  # alpha 14
    ]
